### ISSUE TITLE
ActiveModel::UnknownAttributeError: unknown attribute 'headhunter' for JobOpportunity.

### ISSUE THREAD

**Issue by reginadiana** [reginadiana/rental-cars-treina-dev-1#25]
`ActiveModel::UnknownAttributeError: unknown attribute 'headhunter' for JobOpportunity.`

`rails g migration add_something_to_other_thing something:references`

`rails db:migration`

```
class other thing
     belog_to: something
end
```

**Comment by Diana-ops** [comment]
Mais problemas com migracao e factory bot:

```
     Failure/Error: candidate = create(:candidate)
     
     NoMethodError:
       undefined method `level=' for #<Candidate:0x02bb7158>
       Did you mean?  level_id=
```

Para resolver, va ate o model de candidate e insira o belongs_to para level:
```

class Candidate < ApplicationRecord
	belongs_to :level
end
```
